spring.application.name=nyumbalink
spring.datasource.url=jdbc:mysql://localhost:3306/nyumbalink
spring.datasource.username=nyumbalink_user
spring.datasource.password=nyumbalink123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=NyumbaLinkSuperSecretKeyForDevelopmentOnly123456789
jwt.expiration=3600000

server.port=8080